[package]
name = "antons-gbc-emu"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
arr_macro = "0.2.1"
bytes = "1.11.1"
cpal = "0.17.3"
cxx = "1.0.194"
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = "0.33.3"
env_logger = "0.11.10"
# iced = {version="0.14.0", features=["image", "advanced"]}
lazy_static = "1.5.0"
rfd = "0.17.2"
serde = "1.0.228"
serde_json = "1.0.149"
smol_str = "0.3.6"
# tinyaudio = "2.0.0"

[build-dependencies]
cxx-build = "1.0.194"