name: Build and Test Script
run-name: Push by @${{ github.actor }}
on: [push]

jobs:
  Build Desktop:
    runs-on: node
    defaults:
      run:
        shell: sh
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: apk add bash
      - run: apk add curl
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: apk add git
      - run: apk add python3
      - run: apk add py3-jinja2
      - run: apk add g++
      - run: apk add make
      - run: apk add cmake
      - run: apk add alsa-lib-dev
      - run: apk add glfw-dev
      - run: apk add wayland-dev
      - run: apk add libxkbcommon-dev
      - run: apk add libx11-dev
      - run: apk add libxrandr-dev
      - run: apk add libxinerama-dev
      - run: apk add libxcursor-dev
      - run: apk add libxi-dev
      - run: apk add libunwind-dev
      - run: mkdir -p build
      - name: Configure
        working-directory: ./build
        run: cmake .. -DBUILD_WEB=OFF -DBUILD_GBA=OFF
      - name: Build
        working-directory: ./build
        run: make
  Build Web-App:
    runs-on: node-debian
    defaults:
      run:
        shell: bash
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: ~/.cargo/bin/rustup target add wasm32-unknown-emscripten
      - run: apt-get install cmake --yes
      - run: mkdir -p build
      - uses: https://github.com/emscripten-core/setup-emsdk@v16
      - name: Configure
        working-directory: ./build
        run: emcmake cmake .. -DBUILD_WEB=ON -DBUILD_GBA=OFF
      - name: Build WASM
        working-directory: ./build
        run: make
      - name: Npm dependencies
        working-directory: ./source/web/amsel-web
        run: npm i
      - name: Build Web App
        working-directory: ./source/web/amsel-web
        run: npm run build
  GBA-Test-Suite:
    runs-on: node
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v4
      - run: apk add git
      - run: apk add python3
      - run: apk add py3-jinja2
      - run: apk add g++
      - run: apk add make
      - run: apk add cmake
      - run: mkdir -p build
      - run: mkdir -p test
      - name: Download Tests
        working-directory: ./test
        run: git clone https://github.com/SingleStepTests/ARM7TDMI
      - name: Unpack Tests
        working-directory: ./test/ARM7TDMI/v1
        run: python transcode_json.py
      - name: Configure
        working-directory: ./build
        run: cmake .. -DBUILD_WEB=OFF -DBUILD_GBA=ON
      - name: Build
        working-directory: ./build
        run: make
      - name: Test
        working-directory: ./build
        run: ctest