name: Build and Test Script
run-name: Push by @${{ github.actor }}
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: node
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v4
      - run: apk add python3
      - run: apk add py3-jinja2
      - run: apk add g++
      - run: apk add make
      - run: apk add cmake
      - run: mkdir -p build
      - working-directory: ./build
      - run: cmake ..
      - run: make