name: Build and Test Script
run-name: Push by @${{ github.actor }}
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update
      - run: apt-get install python3
      - run: apt-get install python3-jinja2
      - run: apt-get install cmake
      - run: mkdir -p build
      - run: cd build
      - run: cmake ..
      - run: make